export const CREWCMD_MANAGEMENT_SKILL_METADATA = {
  kind: "service-skill",
  service: "crewcmd-management",
  version: 1,
  category: "operations",
  icon: "🧭",
  reviewSafeByDefault: false,
  auth: {
    type: "runtime-bearer",
    env: "HEARTBEAT_SECRET",
  },
  openclaw: {
    requires: {
      bins: ["curl"],
      env: ["HEARTBEAT_SECRET", "CREWCMD_RUNTIME_ID"],
    },
    primaryEnv: "HEARTBEAT_SECRET",
  },
  capabilities: [
    "tasks:list",
    "tasks:get",
    "tasks:create",
    "tasks:update",
    "tasks:comments:list",
    "tasks:comments:create",
    "tasks:time-entries:list",
    "tasks:time-entries:create",
    "projects:list",
    "projects:create",
    "projects:get",
    "projects:update",
    "agents:list",
    "agents:get",
    "agents:update",
    "agents:start",
    "agents:stop",
    "agents:restart",
    "agents:status",
    "agents:output:get",
    "agents:task:assign",
    "agents:skills:list",
    "agents:skills:create",
    "agents:skills:delete",
    "heartbeat:create",
    "inbox:list",
    "inbox:create",
    "inbox:update",
    "blueprints:list",
    "blueprints:get",
    "blueprints:create",
    "blueprints:launch",
    "docs:list",
    "docs:get",
    "docs:create",
    "docs:update",
    "budgets:list",
    "budgets:get",
    "activity:list",
  ],
  configSchema: {
    type: "object",
    additionalProperties: false,
    properties: {
      baseUrl: {
        type: "string",
        title: "CrewCmd base URL",
        description: "Workspace URL for CrewCmd, for example https://crewcmd.example.com",
      },
      companyId: {
        type: "string",
        title: "Company ID",
        description: "Optional workspace company UUID used when requests need explicit scoping",
      },
      workspaceId: {
        type: "string",
        title: "Workspace ID",
        description: "Preferred workspace UUID for workspace-scoped CrewCmd operations",
      },
      runtimeId: {
        type: "string",
        title: "Runtime ID",
        description: "CrewCmd runtime UUID used to enforce runtime-scoped bearer access",
      },
      defaultAgentId: {
        type: "string",
        title: "Default agent ID",
        description: "Optional default assignee for task operations",
      },
      defaultProjectId: {
        type: "string",
        title: "Default project ID",
        description: "Optional default project context for create/list flows",
      },
      canManageAgents: {
        type: "boolean",
        title: "Allow agent management",
        description: "Enable lifecycle, assignment, and skill-management actions for agents",
        default: true,
      },
      canManageBlueprints: {
        type: "boolean",
        title: "Allow blueprint management",
        description: "Enable blueprint creation and launch actions",
        default: true,
      },
    },
    required: ["baseUrl"],
  },
  configExample: {
    baseUrl: "https://crewcmd.example.com",
    companyId: "company_123",
    workspaceId: "workspace_123",
    runtimeId: "runtime_123",
    canManageAgents: true,
  },
} as const;
