export const CREWCMD_MANAGEMENT_CAPABILITY_CONTRACT = [
  { capability: "tasks:list", method: "GET", path: "/api/tasks", notes: "List tasks in an explicit workspace scope." },
  { capability: "tasks:get", method: "GET", path: "/api/tasks/{id}", notes: "Read a task by UUID or short ID." },
  { capability: "tasks:create", method: "POST", path: "/api/tasks", notes: "Create a task in the explicit workspace scope." },
  { capability: "tasks:update", method: "PATCH", path: "/api/tasks/{id}", notes: "Update task status, assignment, metadata, or review fields." },
  { capability: "tasks:complete", method: "POST", path: "/api/tasks/{id}/complete", notes: "Submit a structured completion report for supervisor validation." },
  { capability: "tasks:comments:list", method: "GET", path: "/api/tasks/{id}/comments", notes: "Read task audit-trail comments." },
  { capability: "tasks:comments:create", method: "POST", path: "/api/tasks/{id}/comments", notes: "Append task progress, blocker, or review context." },
  { capability: "tasks:time-entries:list", method: "GET", path: "/api/tasks/{id}/time-entries", notes: "Read task time entries." },
  { capability: "tasks:time-entries:create", method: "POST", path: "/api/tasks/{id}/time-entries", notes: "Create a task time entry." },
  { capability: "projects:list", method: "GET", path: "/api/projects", notes: "List projects in an explicit workspace scope." },
  { capability: "projects:create", method: "POST", path: "/api/projects", notes: "Create a project in an explicit workspace scope." },
  { capability: "projects:get", method: "GET", path: "/api/projects/{id}", notes: "Read project detail." },
  { capability: "projects:update", method: "PATCH", path: "/api/projects/{id}", notes: "Update project detail." },
  { capability: "agents:list", method: "GET", path: "/api/agents", notes: "List agents in an explicit workspace scope." },
  { capability: "agents:get", method: "GET", path: "/api/agents/{callsign}", notes: "Read an agent by callsign." },
  { capability: "agents:update", method: "PATCH", path: "/api/agents/{callsign}", notes: "Update an agent by callsign." },
  { capability: "agents:start", method: "POST", path: "/api/agents/{callsign}/start", notes: "Start an agent runtime process." },
  { capability: "agents:stop", method: "POST", path: "/api/agents/{callsign}/stop", notes: "Stop an agent runtime process." },
  { capability: "agents:restart", method: "POST", path: "/api/agents/{callsign}/restart", notes: "Restart an agent runtime process." },
  { capability: "agents:status", method: "GET", path: "/api/agents/{callsign}/status", notes: "Read runtime status for an agent." },
  { capability: "agents:output:get", method: "GET", path: "/api/agents/{callsign}/output", notes: "Read captured agent output." },
  { capability: "agents:task:assign", method: "POST", path: "/api/agents/{callsign}/task", notes: "Dispatch explicit task instructions to an agent." },
  { capability: "agents:skills:list", method: "GET", path: "/api/agents/{callsign}/skills", notes: "List skills assigned to an agent." },
  { capability: "agents:skills:create", method: "POST", path: "/api/agents/{callsign}/skills", notes: "Assign a skill to an agent." },
  { capability: "agents:skills:delete", method: "DELETE", path: "/api/agents/{callsign}/skills/{skillId}", notes: "Remove an assigned skill from an agent." },
  { capability: "heartbeat:create", method: "POST", path: "/api/agents/heartbeat", notes: "Publish runtime heartbeat status." },
  { capability: "inbox:list", method: "GET", path: "/api/inbox", notes: "List inbox messages in an explicit workspace scope." },
  { capability: "inbox:create", method: "POST", path: "/api/inbox", notes: "Create a human or agent inbox message." },
  { capability: "inbox:update", method: "PATCH", path: "/api/inbox/{id}", notes: "Update inbox message status or action result." },
  { capability: "blueprints:list", method: "GET", path: "/api/blueprints", notes: "List built-in and custom blueprints." },
  { capability: "blueprints:get", method: "GET", path: "/api/blueprints/{id}", notes: "Read blueprint detail." },
  { capability: "blueprints:create", method: "POST", path: "/api/blueprints", notes: "Create a custom blueprint." },
  { capability: "blueprints:launch", method: "POST", path: "/api/blueprints/deploy", notes: "Deploy a blueprint into a workspace or company context." },
  { capability: "docs:list", method: "GET", path: "/api/docs", notes: "List workspace documents." },
  { capability: "docs:get", method: "GET", path: "/api/docs/{id}", notes: "Read document detail." },
  { capability: "docs:create", method: "POST", path: "/api/docs", notes: "Create a workspace document." },
  { capability: "docs:update", method: "PATCH", path: "/api/docs/{id}", notes: "Update a workspace document." },
  { capability: "budgets:list", method: "GET", path: "/api/budgets", notes: "List budget records available to the current scope." },
  { capability: "budgets:get", method: "GET", path: "/api/budgets/{agentId}", notes: "Read budget detail for an agent." },
  { capability: "activity:list", method: "GET", path: "/api/activity", notes: "List activity log entries." },
] as const;

export const CREWCMD_MANAGEMENT_SKILL_METADATA = {
  kind: "service-skill",
  service: "crewcmd-management",
  version: 1,
  category: "operations",
  icon: "🧭",
  reviewSafeByDefault: false,
  auth: {
    type: "runtime-bearer",
    env: "HEARTBEAT_SECRET",
  },
  openclaw: {
    requires: {
      bins: ["curl"],
      env: ["HEARTBEAT_SECRET", "CREWCMD_RUNTIME_ID"],
    },
    primaryEnv: "HEARTBEAT_SECRET",
  },
  capabilities: CREWCMD_MANAGEMENT_CAPABILITY_CONTRACT.map((entry) => entry.capability),
  configSchema: {
    type: "object",
    additionalProperties: false,
    properties: {
      baseUrl: {
        type: "string",
        title: "CrewCmd base URL",
        description: "Workspace URL for CrewCmd, for example https://crewcmd.example.com",
      },
      companyId: {
        type: "string",
        title: "Company ID",
        description: "Optional workspace company UUID used when requests need explicit scoping",
      },
      workspaceId: {
        type: "string",
        title: "Workspace ID",
        description: "Preferred workspace UUID for workspace-scoped CrewCmd operations",
      },
      runtimeId: {
        type: "string",
        title: "Runtime ID",
        description: "CrewCmd runtime UUID used to enforce runtime-scoped bearer access",
      },
      defaultAgentId: {
        type: "string",
        title: "Default agent ID",
        description: "Optional default assignee for task operations",
      },
      defaultProjectId: {
        type: "string",
        title: "Default project ID",
        description: "Optional default project context for create/list flows",
      },
      canManageAgents: {
        type: "boolean",
        title: "Allow agent management",
        description: "Enable lifecycle, assignment, and skill-management actions for agents",
        default: true,
      },
      canManageBlueprints: {
        type: "boolean",
        title: "Allow blueprint management",
        description: "Enable blueprint creation and launch actions",
        default: true,
      },
    },
    required: ["baseUrl"],
  },
  configExample: {
    baseUrl: "https://crewcmd.example.com",
    companyId: "company_123",
    workspaceId: "workspace_123",
    runtimeId: "runtime_123",
    canManageAgents: true,
  },
} as const;
